spring:
  profiles:
    active: dev # active profile by default is dev. in production,it will be replaced by prod by azure environment variable
server:
  port: 80

api:
  endpoint:
    base-url: "/api/v1"


