name: build and deploy a container to Azure web app

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: hogwarts-artifacts-online

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu_latest

    steps:
      - name: check out the repository
        uses: actions/checkout@v4
      - name: setup java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: build with maven
        run: mvn --batch-mode --update-snapshots package -Dskiptests
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: log in github container registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{  secrets.GITHUB_TOKEN }}
      - name: lowercase the repository
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tag: ghcr.io/${{ env.repo }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: lower case the repository name
        uses: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: deploy to azure wep app
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.repo }}:${{ github.sha }}'

